import React from 'react';
import SplashScreen from 'react-native-splash-screen';
import { createAppContainer } from 'react-navigation';
import { createDrawerNavigator } from 'react-navigation-drawer';
import { createStackNavigator } from 'react-navigation-stack';
import { fadeIn } from 'react-navigation-transitions';
import { withTheme } from './src/app/theme/themeProvider';
import { ThemeContextProvider } from './src/app/theme/themeProvider';
import { Navigation } from "./src/app/components/config";

import {
    HomeView,
    CategoriesView,
    SubCategoriesView,
    ToolsView,
    ToolsWorkersView,
    WorkersView,
    ScheduleView,
    AbsencesView,
    SettingsView,
    ChangeTheme,
    AboutUs,
    AppIntro,
    AppVersion,
    ImportData,
    ExportData,
    AboutApp,
    AboutHome,
    AboutCategories,
    AboutCategorySearch,
    AboutCategoryCreate,
    AboutCategoryUpdate,
    AboutCategoryDelete,
    AboutSubCategories,
    AboutSubCategorySearch,
    AboutSubCategoryCreate,
    AboutSubCategoryUpdate,
    AboutSubCategoryDelete,
    AboutTools,
    AboutToolSearch,
    AboutToolCreate,
    AboutToolRead,
    AboutToolUpdate,
    AboutToolDelete,
    AboutToolsWorkers,
    AboutToolsWorkersReturn,
    AboutToolsWorkersSearch,
    AboutToolsWorkersCreate,
    AboutToolsWorkersRead,
    AboutToolsWorkersDelete,
    AboutWorkers,
    AboutWorkerSearch,
    AboutWorkerCreate,
    AboutWorkerRead,
    AboutWorkerUpdate,
    AboutWorkerDelete,
    createWorker,
    readWorker,
    updateWorker,
    deleteWorker,
    searchWorker,
    createCategory,
    updateCategory,
    deleteCategory,
    searchCategory,
    createSubCategory,
    updateSubCategory,
    deleteSubCategory,
    searchSubCategory,
    createTool,
    readTool,
    updateTool,
    deleteTool,
    searchTool,
    createToolWorker,
    readToolWorker,
    returnToolWorker,
    deleteToolWorker,
    searchToolWorker,
    AboutSchedule,
    AboutScheduleCreate,
    AboutScheduleRead,
    AboutScheduleUpdate,
    AboutScheduleDelete,
    AboutAbsences,
    AboutAbsenceCreate,
    AboutAbsenceRead,
    AboutAbsenceUpdate,
    AboutAbsenceDelete,
    AboutSettings,
    AboutAppIntro,
    AboutAppUs,
    AboutAppContacts,
    AboutAppVersion,
    createSchedule,
    readSchedule,
    updateSchedule,
    deleteSchedule,
    createAbsence,
    readAbsence,
    updateAbsence,
    deleteAbsence,
} from './src/app/views/config';

export default class App extends React.Component {
    componentDidMount() {
        SplashScreen.hide();
    }

    render() {
        return (
            <ThemeContextProvider>
                <AppContainerWithTheme />
            </ThemeContextProvider>
        );
    }
}

const StackNavigator = createStackNavigator(
    {
        WorkersView: { screen: WorkersView },
        createWorker: { screen: createWorker },
        readWorker: { screen: readWorker },
        updateWorker: { screen: updateWorker },
        deleteWorker: { screen: deleteWorker },
        searchWorker: { screen: searchWorker },
        createCategory: { screen: createCategory },
        updateCategory: { screen: updateCategory },
        deleteCategory: { screen: deleteCategory },
        searchCategory: { screen: searchCategory },
        createSubCategory: { screen: createSubCategory },
        updateSubCategory: { screen: updateSubCategory },
        deleteSubCategory: { screen: deleteSubCategory },
        searchSubCategory: { screen: searchSubCategory },
        createTool: { screen: createTool },
        readTool: { screen: readTool },
        updateTool: { screen: updateTool },
        deleteTool: { screen: deleteTool },
        searchTool: { screen: searchTool },
        createToolWorker: { screen: createToolWorker },
        readToolWorker: { screen: readToolWorker },
        returnToolWorker: { screen: returnToolWorker },
        deleteToolWorker: { screen: deleteToolWorker },
        searchToolWorker: { screen: searchToolWorker },
        createSchedule: { screen: createSchedule },
        readSchedule: { screen: readSchedule },
        updateSchedule: { screen: updateSchedule },
        deleteSchedule: { screen: deleteSchedule },
        createAbsence: { screen: createAbsence },
        readAbsence: { screen: readAbsence },
        updateAbsence: { screen: updateAbsence },
        deleteAbsence: { screen: deleteAbsence },
        SubCategoriesView: { screen: SubCategoriesView },
        AbsencesView: { screen: AbsencesView },
        CategoriesView: { screen: CategoriesView },
        ChangeTheme: { screen: ChangeTheme },
        AboutUs: { screen: AboutUs },
        AppIntro: { screen: AppIntro },
        AboutApp: { screen: AboutApp },
        AppVersion: { screen: AppVersion },
        ImportData: { screen: ImportData },
        ExportData: { screen: ExportData },
        AboutHome: { screen: AboutHome },
        AboutCategories: { screen: AboutCategories },
        AboutCategorySearch: { screen: AboutCategorySearch },
        AboutCategoryCreate: { screen: AboutCategoryCreate },
        AboutCategoryUpdate: { screen: AboutCategoryUpdate },
        AboutCategoryDelete: { screen: AboutCategoryDelete },
        AboutSubCategories: { screen: AboutSubCategories },
        AboutSubCategorySearch: { screen: AboutSubCategorySearch },
        AboutSubCategoryCreate: { screen: AboutSubCategoryCreate },
        AboutSubCategoryUpdate: { screen: AboutSubCategoryUpdate },
        AboutSubCategoryDelete: { screen: AboutSubCategoryDelete },
        AboutTools: { screen: AboutTools },
        AboutToolSearch: { screen: AboutToolSearch },
        AboutToolCreate: { screen: AboutToolCreate },
        AboutToolRead: { screen: AboutToolRead },
        AboutToolUpdate: { screen: AboutToolUpdate },
        AboutToolDelete: { screen: AboutToolDelete },
        AboutToolsWorkers: { screen: AboutToolsWorkers },
        AboutToolsWorkersReturn: { screen: AboutToolsWorkersReturn },
        AboutToolsWorkersSearch: { screen: AboutToolsWorkersSearch },
        AboutToolsWorkersCreate: { screen: AboutToolsWorkersCreate },
        AboutToolsWorkersRead: { screen: AboutToolsWorkersRead },
        AboutToolsWorkersDelete: { screen: AboutToolsWorkersDelete },
        AboutWorkers: { screen: AboutWorkers },
        AboutWorkerSearch: { screen: AboutWorkerSearch },
        AboutWorkerCreate: { screen: AboutWorkerCreate },
        AboutWorkerRead: { screen: AboutWorkerRead },
        AboutWorkerUpdate: { screen: AboutWorkerUpdate },
        AboutWorkerDelete: { screen: AboutWorkerDelete },
        AboutSchedule: { screen: AboutSchedule },
        AboutScheduleCreate: { screen: AboutScheduleCreate },
        AboutScheduleRead: { screen: AboutScheduleRead },
        AboutScheduleUpdate: { screen: AboutScheduleUpdate },
        AboutScheduleDelete: { screen: AboutScheduleDelete },
        AboutAbsences: { screen: AboutAbsences },
        AboutAbsenceCreate: { screen: AboutAbsenceCreate },
        AboutAbsenceRead: { screen: AboutAbsenceRead },
        AboutAbsenceUpdate: { screen: AboutAbsenceUpdate },
        AboutAbsenceDelete: { screen: AboutAbsenceDelete },
        AboutSettings: { screen: AboutSettings },
        AboutAppVersion: { screen: AboutAppVersion },
        AboutAppIntro: { screen: AboutAppIntro },
        AboutAppUs: { screen: AboutAppUs },
        AboutAppContacts: { screen: AboutAppContacts },
    },
    {
        transitionConfig: () => fadeIn(),
    }
);

const DrawerNavigator = createDrawerNavigator(
    {
        Home: { screen: HomeView },
        Categories: { screen: CategoriesView },
        SubCategories: { screen: SubCategoriesView, navigationOptions: { drawerLabel: () => null } },
        Tools: { screen: ToolsView, navigationOptions: { drawerLabel: () => null } },
        ToolsWorkersView: { screen: ToolsWorkersView },
        Workers: { screen: WorkersView },
        Schedule: { screen: ScheduleView },
        Absences: { screen: AbsencesView },
        Settings: { screen: SettingsView },
        StackNavigator: { screen: StackNavigator, navigationOptions: { drawerLabel: () => null } }
    },
    {
        initialRouteName: 'Home',
        drawerOpenRoute: "DrawerOpen",
        drawerCloseRoute: "DrawerClose",
        drawerToggleRoute: "DrawerToggle",
        contentComponent: Navigation,
        contentOptions: {
            activeTintColor: 'transparent',
            activeBackgroundColor: '#2EBEE5',
            inactiveTintColor: 'transparent',
            inactiveBackgroundColor: 'transparent',
            iconContainerStyle: {
                color: 'red'
            }
        },
        drawerType: 'front',
        statusBarAnimation: 'slide',
        minSwipeDistance: 5,
    }
);

const AppContainer = createAppContainer(DrawerNavigator, StackNavigator);
const AppContainerWithTheme = withTheme(({ theme }) => {
    return <AppContainer screenProps={{ theme }} />;
});
